### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED

### ISSUE THREAD

**Issue by SancheZ25RUS** [acherkashin/yandex-music-extension#98]
Host
OS Name	Microsoft Windows 11 Pro N
Version	10.0.22621 Build 22621

WSL
OS: Ubuntu 22.04.2 LTS on Windows 10 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2

VSCode
Version: 1.79.2 (system setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

---

При попытке воспроизведения музыки через extension:
```
[YandexMusicExtension I] Starting extension v0.15.2
[YandexMusicExtension I] Electron is already downloaded to default location. See https://github.com/electron/get#how-it-works
[YandexMusicExtension I] Archive already extracted: "/home/sanchez/.vscode-server/extensions/acherkashin.yandex-music-extension-0.15.2/out/electron/dist"
[YandexMusicExtension I] {"showElectronApp":false}
[YandexMusicExtension I] Starting electron: "/home/sanchez/.vscode-server/extensions/acherkashin.yandex-music-extension-0.15.2/out/electron/dist/electron /home/sanchez/.vscode-server/extensions/acherkashin.yandex-music-extension-0.15.2/out/electron/main.js eyJzaG93RWxlY3Ryb25BcHAiOmZhbHNlfQ=="
[YandexMusicExtension I] exited with code: 127 and signal: null
[YandexMusicExtension E] Error: Channel closed
	at new NodeError (node:internal/errors:387:5)
	at ChildProcess.target.send (node:internal/child_process:742:16)
	at ElectronPlayer.play (/home/sanchez/.vscode-server/extensions/acherkashin.yandex-music-extension-0.15.2/out/players/electronPlayer.js:80:74)
	at Store.<anonymous> (/home/sanchez/.vscode-server/extensions/acherkashin.yandex-music-extension-0.15.2/out/store.js:368:29)
	at Generator.next (<anonymous>)
	at fulfilled (/home/sanchez/.vscode-server/extensions/acherkashin.yandex-music-extension-0.15.2/out/store.js:11:58)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by lyaguxafrog** [comment]
#14
